// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback constants ensure the published build still initializes even if
// VITE_* env vars are not inlined at build time. These are publishable values
// (anon key is safe to ship to the client).
const FALLBACK_SUPABASE_URL = "https://ybfsnmvxuxdifjmpfcph.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZnNubXZ4dXhkaWZqbXBmY3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjczNTQ1NTksImV4cCI6MjA4MjkzMDU1OX0.z0ktO8JPdC8Q7JObUNP0UxFyLCLyS9B5zgqkscF1cKo";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL) {
  throw new Error("[Supabase] Missing VITE_SUPABASE_URL — env var was not inlined at build time and no fallback is configured.");
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("[Supabase] Missing VITE_SUPABASE_PUBLISHABLE_KEY — env var was not inlined at build time and no fallback is configured.");
}

// Safe localStorage adapter — falls back to in-memory when storage is blocked
// (sandboxed iframes, private browsing, cross-origin contexts)
const safeStorage = (() => {
  const mem: Record<string, string> = {};
  let useLocal = true;
  try {
    localStorage.setItem('__test__', '1');
    localStorage.removeItem('__test__');
  } catch {
    useLocal = false;
  }
  return {
    getItem: (key: string) => {
      if (useLocal) { try { return localStorage.getItem(key); } catch { useLocal = false; } }
      return mem[key] ?? null;
    },
    setItem: (key: string, value: string) => {
      if (useLocal) { try { localStorage.setItem(key, value); return; } catch { useLocal = false; } }
      mem[key] = value;
    },
    removeItem: (key: string) => {
      if (useLocal) { try { localStorage.removeItem(key); return; } catch { useLocal = false; } }
      delete mem[key];
    },
  };
})();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
